openapi: 3.0.3
info:
  title: Data Access API
  version: 1.0.0
paths:
  /query:
    post:
      summary: Submit a structured SQL-like query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - columns
                - schema
                - operation
                - table
              properties:
                columns:
                  type: array
                  items:
                    type: string
                  description: List of columns to select
                joins:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - table
                      - on
                    properties:
                      type:
                        type: string
                        enum: [INNER, LEFT, RIGHT, FULL]
                        description: Type of SQL join
                      table:
                        type: string
                        description: Table to join
                      on:
                        type: string
                        description: Join condition
                schema:
                  type: string
                  description: Schema of the table
                operation:
                  type: string
                  enum: [SELECT]
                  description: SQL operation (only SELECT supported)
                table:
                  type: string
                  description: Target table
                where:
                  type: string
                  description: SQL WHERE clause
      responses:
        '200':
          description: Query received successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Query parsed successfully
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Invalid query payload
